name: "Build and deploy website"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: ["main"]

permissions:
  contents: "write"

jobs:
  build-site:
    runs-on: "ubuntu-latest"
    steps:
    - name: "Checkout repository"
      uses: actions/checkout@v2

    - name: "Install uv"
      uses: astral-sh/setup-uv@v6
      with:
        version: "0.7.21"
        enable-cache: true

    - name: "Set up Python"
      uses: actions/setup-python@v5

    - name: "Install the project via uv"
      run: uv sync --locked --with docs

    - name: "Check site builds"
      run: uv run mkdocs build

    - name: "Deploy site to GitHub pages"
      # if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
      run: uv run mkdocs gh-deploy
